src/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from .import views

app_name = 'account'
urlpatterns = [
    path('register/', views.register, name='register'),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    path('login/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

src/bing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from . import views

app_name = 'bing'
urlpatterns = [
    path('', cache_page(60 * 15)(views.IndexView.as_view()), name='index'),
    path('detail/<hsh>/', cache_page(60 * 15)(views.detail), name='detail'),
]

src/home/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', TemplateView.as_view(template_name='home/about.html'), name='about'),
]

src/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('bing/', include('bing.urls', namespace='bing')),
    path('soul/', include('soul.urls', namespace='soul')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'website.error_views.handler404'
handler500 = 'website.error_views.handler500'

admin.site.site_title = "Attention Admin"
admin.site.site_header = "Attention Admin"

src/wechat/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'wechat'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
]

src/templates/back_to_top.html
<button type="button" id="BackTop" class="toTop-arrow btn btn-info" style="z-index: 100;">
    <i class="fas fa-arrow-up"></i>
</button>

<script>
    // 向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({ scrollTop: 0 }, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 2.8rem;
        height: 2.8rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 50%;
        opacity: 0.8;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

src/templates/base.html
{% extends 'bootstrap4/bootstrap4.html' %}

{% load staticfiles %}

{% load bootstrap4 %}

{% bootstrap_javascript jquery='full' %}

{% block bootstrap4_extra_head %}
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/icon/icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="96x96" href="{% static 'images/icon/icon-96x96.png' %}">
<link rel="apple-touch-icon" sizes="128x128" href="{% static 'images/icon/icon-128x128.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'images/icon/icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'images/icon/icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="192x192" href="{% static 'images/icon/icon-192x192.png' %}">
<link rel="apple-touch-icon" sizes="384x384" href="{% static 'images/icon/icon-384x384.png' %}">
<link rel="apple-touch-icon" sizes="512x512" href="{% static 'images/icon/icon-512x512.png' %}">
<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
<link rel="manifest" href="{% static 'manifest.json' %}">

<link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/5.8.1/css/all.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.6/css/mdb.min.css" />

<meta property="og:title" content="hippieZhou">
<meta property="og:description" content="Tks for your attention.">
<meta name="og:url" content="https://hippiezhou.fun">
<meta name="robots" content="index,follow">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="transparent">
{% endblock %}

{% block bootstrap4_title %}
{% block title %}hippieZhou{% endblock %}
{% endblock %}


{% block bootstrap4_before_content %}
{% include "nav.html" %}
{% endblock %}

{% block bootstrap4_content %}
<main>
    <div class="container my-5">
        {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}

        {% block content %}{% endblock %}
    </div>
    {% include 'back_to_top.html' %}
</main>
{% endblock %}

{% block bootstrap4_after_content %}
{% include "footer.html" %}
{% endblock %}

{% block bootstrap4_extra_script %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.6/js/mdb.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script>
    function csrfSafeMethon(method) {
        // 如下的HTTP请求不需要设置CRSF信息
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethon(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
            }
        }
    });
    
    // 检测浏览器是否支持SW
    if (navigator.serviceWorker != null) {
        navigator.serviceWorker.register("{% static 'sw.js' %}")
            .then(function (registartion) {
                console.log('支持sw:', registartion.scope)
            })
    }

    $(document).ready(function () {
        {% block domready %} {% endblock %}
    });
</script>
{% endblock %}

src/templates/footer.html
<footer>
    <div class="container">
        <hr>
        <p>Do what you want and love what your love !</p>
        <p><i class="far fa-smile-beam fa-spin"></i> Developed by <a href="https://www.djangoproject.com/">Django</a>
            and
            <a href="https://mdbootstrap.com">DMB</a>.</p>
        <div class="text-center">
            <p>© 2019 Copyright: <a href="/">hippieZhou</a></p>
        </div>
    </div>
</footer>

src/templates/nav.html
<header>
    <nav class="navbar navbar-expand-lg navbar-dark black">
        <div class="container">
            <a href="/" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                    stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2"
                    viewBox="0 0 24 24" focusable="false">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Attention</strong>
            </a>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbars"
                aria-controls="navbars" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse collapse" id="navbars">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {% ifequal  '/bing' request.path|slice:':5' %} active {% endifequal %}">
                        <a class="nav-link" href="{% url 'bing:index' %}"><i class="far fa-images mr-1"></i>壁纸</a>
                    </li>
                    <li class="nav-item {% ifequal  '/soul' request.path|slice:':5' %} active {% endifequal %}">
                        <a class="nav-link" href="{% url 'soul:index' %}"><i class="fas fa-ghost mr-1"></i>鸡汤</a>
                    </li>
                    <li class="nav-item {% ifequal  '/blog' request.path|slice:':5' %} active {% endifequal %}">
                        <a class="nav-link" href="{% url 'blog:index' %}"><i class="fas fa-quran mr-1"></i>博客</a>
                    </li>
                    <li class="nav-item {% ifequal '/about' request.path|slice:':6' %} active {% endifequal %}">
                        <a class="nav-link" href="{% url 'home:about' %}"><i class="fas fa-user-ninja mr-1"></i>关于</a>
                    </li>
                </ul>

                <ul class="navbar-nav nav-flex-icons">
                    {% if request.user.is_authenticated  %}
                    <li class="nav-item">
                        <a href="{% url 'account:logout' %}" class="nav-link"><i class="fas fa-sign-in-alt"></i></a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'account:login' %}" class="nav-link"><i class="fas fa-user"></i></a>
                    </li>
                    <!--
                    <li class="nav-item">
                        <a href="{% url 'account:register' %}" class="nav-link"><i class="far fa-registered"></i></a>
                    </li>
                    -->
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

src/templates/pagination.html
{% if is_paginated %}
<nav class="Page navigation">
    <ul class="pagination pg-blue justify-content-center">

        <!--头部-->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link m-1" aria-label="Previous"
                href="{{ request.path }}?page={{ page_obj.previous_page_number }}">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled m-1">
            <a class="page-link" aria-label="Previous" href="#">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}

        <!--中间页码-->
        {% if page_obj.number >= 5 %}
        <li class="page-item m-1"><a class="page-link" href="?page=1">1</a></li>
        <li class="page-item m-1"><span>...</span></li>
        {% elif page_obj.number == 4 %}
        <li class="page-item m-1"><a class="page-link" href="?page=1">1</a></li>
        {% endif %}
        {% if page_obj.number|add:"-2" >= 1  %}
        <li class="page-item m-1"><a class="page-link"
                href="?page={{ page_obj.number|add:"-2" }}">{{ page_obj.number|add:"-2" }}</a>
        </li>
        {% endif %}
        {% if page_obj.number|add:"-1" >= 1  %}
        <li class="page-item m-1"><a class="page-link"
                href="?page={{ page_obj.number|add:"-1" }}">{{ page_obj.number|add:"-1" }}</a>
        </li>
        {% endif %}
        <li class="page-item active m-1"><a class="page-link"
                href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
        {% if page_obj.number|add:"1" <= paginator.num_pages  %}
        <li class="page-item m-1"><a class="page-link"
                href="?page={{ page_obj.number|add:"1" }}">{{ page_obj.number|add:"1" }}</a>
        </li>
        {% endif %}
        {% if page_obj.number|add:"2" <= paginator.num_pages %}
        <li class="page-item m-1"><a class="page-link"
                href="?page={{ page_obj.number|add:"2" }}">{{ page_obj.number|add:"2" }}</a>
        </li>
        {% endif %}
        {% if page_obj.number|add:"2" <= paginator.num_pages|add:"-2" %}
        <li class="page-item m-1"><span>...</span></li>
        <li class="page-item m-1"><a class="page-link"
                href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
        {% elif page_obj.number|add:"1" <= paginator.num_pages|add:"-2" %}
        <li class="page-item m-1"><a class="page-link"
                href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
        {% endif %}

        <!--尾部-->
        {% if page_obj.has_next %}
        <li class="page-item m-1 {% if not page_obj.has_next %} disabled {% endif %}">
            <a class="page-link" aria-label="Next" href="{{ request.path }}?page={{ page_obj.next_page_number  }}">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled m-1">
            <a class="page-link" aria-label="Next" href="#">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}

    </ul>
</nav>
{% endif %}