src/bing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from . import views

app_name = 'bing'
urlpatterns = [
    path('', cache_page(60 * 15)(views.IndexView.as_view()), name='index'),
    path('detail/<hsh>/', cache_page(60 * 15)(views.detail), name='detail'),
]

src/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('bing/', include('bing.urls', namespace='bing')),
    path('soul/', include('soul.urls', namespace='soul')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'website.error_views.handler404'
handler500 = 'website.error_views.handler500'

admin.site.site_title = "Attention Admin"
admin.site.site_header = "Attention Admin"

src/bing/models.py
from django.db import models

# Create your models here.


class Wallpaper(models.Model):
    hsh = models.CharField(verbose_name='唯一标识', max_length=48)

    title = models.CharField(verbose_name='标题', max_length=100)
    caption = models.CharField(verbose_name='主题', max_length=100)
    desc = models.TextField(verbose_name='内容')

    copyright = models.CharField(verbose_name='完整版权信息', max_length=200)
    copyrightonly = models.CharField(verbose_name='基本版权信息', max_length=100)
    copyrightlink = models.URLField(verbose_name='版权地址')

    datetime = models.DateTimeField(verbose_name='日期')

    quiz = models.URLField(verbose_name='详情地址')
    url = models.URLField(verbose_name='图片地址')
    urlbase = models.URLField(verbose_name='基地址')

    class Meta:
        verbose_name = "必应壁纸"
        verbose_name_plural = verbose_name
        ordering = ('-datetime',)

    def __str__(self):
        return self.title

src/bing/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from datetime import datetime

from .models import Wallpaper
# Create your views here.


class IndexView(generic.ListView):
    template_name = 'bing/index.html'
    context_object_name = 'wallpapers'
    paginate_by = 9

    def get_queryset(self):
        has = Wallpaper.objects.filter(
            datetime__contains=timezone.now().date())
        if has.count() == 0:
            print('sipder is running')
            from .spider import spider
            spider()
        return Wallpaper.objects.all()


def detail(request, hsh):
    wallpaper = get_object_or_404(Wallpaper, hsh=hsh)
    return render(request, 'bing/detail.html', {'wallpaper': wallpaper})

src/templates/bing/detail.html
{% extends 'base.html' %}
{% load bing_tags %}

{% block content %}
<div class="jumbotron text-center">
    <h4 class="card-title font-bold pb-2"><strong>{{ wallpaper.title }}</strong></h4>
    <div class="view overlay my-4">
        <img id="img" src="{{ wallpaper.url|bingimage }}" class="img-fluid" alt="">
        <a>
            <div class="mask rgba-white-slight"></div>
        </a>
    </div>
    <h5 class="indigo-text font-bold mb-4">{{ wallpaper.copyrightonly }}</h5>
    <figcaption class="figure-caption text-center mb-4">{{ wallpaper.datetime|date:'Y-m-d' }}</figcaption>
    <p class="card-text text-left">
        @{{ wallpaper.desc }}
    </p>
    <a class="btn btn-default btn-sm" onclick="download_image(this);">
        <i class="fa fa-download pr-2" aria-hidden="true"></i> Download
    </a>
</div>
{% endblock %}

{% block extra_scripts %}
<script>
    function download_image(btn) {
        var a = document.getElementById("img");
        var src = a.getAttribute("src");

        var x = new XMLHttpRequest();
        x.open("GET", src, true);
        x.responseType = 'blob';
        x.onload = function (e) {
            var url = window.URL.createObjectURL(x.response)
            var a = document.createElement('a');
            a.href = url
            a.download = ''
            a.click()
        }
        x.send();
        return true;
    }
</script>
{% endblock %}

src/templates/bing/index.html
{% extends 'base.html' %}
{% load bing_tags %}

{% block content %}
<div class="row">
    {% for wallpaper in wallpapers %}
    <div class="col-md-4">
        <div class="card mb-4">
            <div class="view overlay zoom">
                <img class="card-img-top" src="{{ wallpaper.url|bingimage }}" alt="{{ wallpaper.copyrightonly }}"
                    srcset="">
                <a>
                    <div class="mask rgba-white-slight waves-effect waves-light"></div>
                </a>
            </div>
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <a class="btn btn-indigo btn-md" href="{% url 'bing:detail' wallpaper.hsh %}">
                        Live Show
                        <i class="fa fa-image ml-1"></i>
                    </a>
                    <small class="text-muted">{{ wallpaper.datetime|date:'Y-m-d' }}</small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% include "pagination.html" %}

{% endblock %}