src/bing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from . import views

app_name = 'bing'
urlpatterns = [
    path('', cache_page(60 * 15)(views.IndexView.as_view()), name='index'),
    path('detail/<hsh>/', cache_page(60 * 15)(views.detail), name='detail'),
]

src/soul/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'wechat'
urlpatterns = [
    path('', views.index, name='index'),
    path('random/', views.random, name='random'),
]

src/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('bing/', include('bing.urls', namespace='bing')),
    path('soul/', include('soul.urls', namespace='soul')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'website.error_views.handler404'
handler500 = 'website.error_views.handler500'

admin.site.site_title = "Attention Admin"
admin.site.site_header = "Attention Admin"

src/soul/models.py
from django.db import models

# Create your models here.

src/soul/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.http import require_GET
from utils.decorators import ajax_required

from home.models import Soul
# Create your views here.


def index(request):
    return render(request, 'soul/index.html', {'soul': Soul.objects.random()})


@ajax_required
@require_GET
def random(request):
    return JsonResponse({'soul': Soul.objects.random().title})

src/templates/soul/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row align-items-center justify-content-center" style="height:60vh;">
    <div class="text-center">
        <h3 id="soul" class="font-weight-bold deep-orange-lighter-hover mb-4">{{ soul }}</h3>
        <a id="next" class="btn btn-sm btn-dark">再来一碗</a>
    </div>
</div>
{% endblock  %}

{% block domready %}
    $('#next').click(function(e){
        e.preventDefault();
        console.log("毒鸡汤，原始数据来自于：https://github.com/egotong/nows");
        $.get('{% url "soul:random" %}',function(data){
            $('#soul').text(data['soul'])
        })
    });
{% endblock %}